FROM node:22.12.0-slim

WORKDIR /app

COPY --chown=app:app package.json package-lock.json ./
RUN ["npm", "install"]

COPY . .

ENV REACT_APP_CLOUDFRONT_URL=https://d24m1jw4p6pn47.cloudfront.net/front_end_assets

ENV NODE_ENV=development

EXPOSE 3000

CMD ["npm", "start"]
